name: Push Release Tags

on:
  push:
    tags:
      - '**'
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    uses: BerkeleyLibrary/.github/.github/workflows/docker-release.yml@v2.0.0
    with:
      image: ghcr.io/${{ github.repository }}
    secrets: inherit
